[package]
name = "reth-evm-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-fs-util.workspace = true

revm.workspace = true
revmc = { workspace = true, features = ["llvm-prefer-dynamic"] }

confy.workspace = true
indexmap = { workspace = true, features = ["serde"] }
libloading = "0.8"
rayon.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
reth-tracing.workspace = true

similar-asserts.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[build-dependencies]
revmc-build.workspace = true

[features]
optimism = ["reth-primitives/optimism", "revm/optimism", "revmc/optimism"]
