[package]
name = "reth-evm-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
revm.workspace = true
revm-jit.workspace = true

confy.workspace = true
libloading = "0.8"
rayon.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
reth-tracing.workspace = true

similar-asserts.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[build-dependencies]
revm-jit-build.workspace = true

[features]
optimism = ["reth-primitives/optimism", "revm/optimism", "revm-jit/optimism"]
