[package]
name = "reth-cli-commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]

[dependencies]
reth-db = { workspace = true, features = ["mdbx"] }
reth-db-api.workspace = true
reth-provider.workspace = true
reth-primitives.workspace = true
reth-node-core.workspace = true
reth-fs-util.workspace = true

# misc
ahash = "0.8"
human_bytes = "0.4.1"
eyre.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

# tui
comfy-table = "7.0"
crossterm = "0.27.0"
ratatui = { version = "0.27", default-features = false, features = [
    "crossterm",
] }