[package]
name = "op-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth-node-builder.workspace = true
reth-cli-util.workspace = true
reth-optimism-cli.workspace = true
reth-provider.workspace = true
reth-optimism-rpc.workspace = true
reth-optimism-node.workspace = true

clap = { workspace = true, features = ["derive", "env"] }

[lints]
workspace = true

[features]
default = ["jemalloc"]

jemalloc = ["reth-cli-util/jemalloc"]
jemalloc-prof = ["reth-cli-util/jemalloc-prof"]
tracy-allocator = ["reth-cli-util/tracy-allocator"]

asm-keccak = ["reth-optimism-cli/asm-keccak", "reth-optimism-node/asm-keccak"]

optimism = ["reth-optimism-cli/optimism", "reth-optimism-node/optimism"]

min-error-logs = ["reth-optimism-cli/min-error-logs"]
min-warn-logs = ["reth-optimism-cli/min-warn-logs"]
min-info-logs = ["reth-optimism-cli/min-info-logs"]
min-debug-logs = ["reth-optimism-cli/min-debug-logs"]
min-trace-logs = ["reth-optimism-cli/min-trace-logs"]

[[bin]]
name = "op-reth"
path = "src/main.rs"
