[package]
name = "reth-ethereum-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-primitives.workspace = true
reth-node-types.workspace = true

[features]
default = ["std"]
std = [
    "reth-primitives/std",
    "reth-node-types/std",
]