[package]
name = "reth-tracing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "tracing helpers"

[lints]
workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "json"] }
tracing-appender.workspace = true
tracing-journald = "0.3"
tracing-logfmt = "0.3.3"
rolling-file = "0.2.0"
eyre.workspace = true
clap = { workspace = true, features = ["derive"] }

# OpenTelemetry
tracing-opentelemetry = { version = "0.27.0", optional = true }
opentelemetry-otlp = { version = "0.26.0", default-features = false, features = ["http", "http-proto", "http-json", "logs", "tokio", "trace"], optional = true }
opentelemetry_sdk = { version = "0.26.0", features = ["rt-tokio", "tokio"], optional = true }
opentelemetry = { version = "0.26.0", optional = true }

[features]
default = ["opentelemetry"]
opentelemetry = [
    "dep:opentelemetry",
    "dep:opentelemetry-otlp",
    "dep:opentelemetry_sdk",
    "dep:tracing-opentelemetry",
]